//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxcToAzure.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AxcToAzure.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string ButtonBack {
            get {
                return ResourceManager.GetString("ButtonBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string ButtonContinue {
            get {
                return ResourceManager.GetString("ButtonContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ButtonExit {
            get {
                return ResourceManager.GetString("ButtonExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string DefaultTaskViewButtonOpen {
            get {
                return ResourceManager.GetString("DefaultTaskViewButtonOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string DefaultTaskViewButtonRefresh {
            get {
                return ResourceManager.GetString("DefaultTaskViewButtonRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the Default Task List.
        /// </summary>
        public static string DefaultTaskViewButtonTexts {
            get {
                return ResourceManager.GetString("DefaultTaskViewButtonTexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defaulttasks.
        /// </summary>
        public static string DefaultTaskViewHeader {
            get {
                return ResourceManager.GetString("DefaultTaskViewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Default Tasks to the User-Stories.
        /// </summary>
        public static string DefaultTaskViewInstruction {
            get {
                return ResourceManager.GetString("DefaultTaskViewInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read File.
        /// </summary>
        public static string ExcelViewButtonReadFile {
            get {
                return ResourceManager.GetString("ExcelViewButtonReadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished!.
        /// </summary>
        public static string ExcelViewFinished {
            get {
                return ResourceManager.GetString("ExcelViewFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Input.
        /// </summary>
        public static string ExcelViewHeader {
            get {
                return ResourceManager.GetString("ExcelViewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to export the Report from Axc.
        /// </summary>
        public static string ExcelViewInstruction {
            get {
                return ResourceManager.GetString("ExcelViewInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column for Itemdescriptions:.
        /// </summary>
        public static string ExcelViewItemDescription {
            get {
                return ResourceManager.GetString("ExcelViewItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. B.
        /// </summary>
        public static string ExcelViewItemDescriptionBlankText {
            get {
                return ResourceManager.GetString("ExcelViewItemDescriptionBlankText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set which column contains the Description of the Items..
        /// </summary>
        public static string ExcelViewItemDescriptionToolTip {
            get {
                return ResourceManager.GetString("ExcelViewItemDescriptionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column for Employees assigned (optional):.
        /// </summary>
        public static string ExcelViewItemEmployee {
            get {
                return ResourceManager.GetString("ExcelViewItemEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. C.
        /// </summary>
        public static string ExcelViewItemEmployeeBlankText {
            get {
                return ResourceManager.GetString("ExcelViewItemEmployeeBlankText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Default Employee (if more than 1):.
        /// </summary>
        public static string ExcelViewItemEmployeeDefault {
            get {
                return ResourceManager.GetString("ExcelViewItemEmployeeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set which employee will be assigned to the items, if there is more than one Employee set.
        ///If the set number is greater than the number of employees, the last Employee one will be assigned
        ///Tasks will be copied for each employee assigned..
        /// </summary>
        public static string ExcelViewItemEmployeeDefaultToolTip {
            get {
                return ResourceManager.GetString("ExcelViewItemEmployeeDefaultToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set which column contains the employee, who will be assigned on the items. 
        ///Format: &apos;Lastname, Firstname&apos; Separate multiple employees with a semicolon &apos;;&apos;.
        /// </summary>
        public static string ExcelViewItemEmployeeToolTip {
            get {
                return ResourceManager.GetString("ExcelViewItemEmployeeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column for Itemnumbers:.
        /// </summary>
        public static string ExcelViewItemNumber {
            get {
                return ResourceManager.GetString("ExcelViewItemNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. D.
        /// </summary>
        public static string ExcelViewItemNumberBlankText {
            get {
                return ResourceManager.GetString("ExcelViewItemNumberBlankText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set which column contains the Projectnumber of the Items..
        /// </summary>
        public static string ExcelViewItemNumberToolTip {
            get {
                return ResourceManager.GetString("ExcelViewItemNumberToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to the Excel-File (.xlsx):.
        /// </summary>
        public static string ExcelViewPath {
            get {
                return ResourceManager.GetString("ExcelViewPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the three dots, then select your Excel File.
        /// </summary>
        public static string ExcelViewPathToolTip {
            get {
                return ResourceManager.GetString("ExcelViewPathToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the Worksheet:.
        /// </summary>
        public static string ExcelViewWorksheetName {
            get {
                return ResourceManager.GetString("ExcelViewWorksheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select which worksheet contains the informations..
        /// </summary>
        public static string ExcelViewWorksheetNameToolTip {
            get {
                return ResourceManager.GetString("ExcelViewWorksheetNameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Itemselection.
        /// </summary>
        public static string ItemSelectViewHeader {
            get {
                return ResourceManager.GetString("ItemSelectViewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select which items should be processed.
        /// </summary>
        public static string ItemSelectViewInstruction {
            get {
                return ResourceManager.GetString("ItemSelectViewInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the Application Language to German?
        ///(Default Language: English).
        /// </summary>
        public static string MessageSetLanguage {
            get {
                return ResourceManager.GetString("MessageSetLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Selection.
        /// </summary>
        public static string MessageSetLanguageHeader {
            get {
                return ResourceManager.GetString("MessageSetLanguageHeader", resourceCulture);
            }
        }
    }
}
