//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxcToAzure.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources___Copy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources___Copy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AxcToAzure.Properties.Resources - Copy", typeof(Resources___Copy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backlog not found..
        /// </summary>
        public static string ApiConnectorBacklogNotFound {
            get {
                return ResourceManager.GetString("ApiConnectorBacklogNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on item:.
        /// </summary>
        public static string ApiConnectorErrorOnItem {
            get {
                return ResourceManager.GetString("ApiConnectorErrorOnItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to continue with the next item?.
        /// </summary>
        public static string ApiConnectorErrorOnItemContinue {
            get {
                return ResourceManager.GetString("ApiConnectorErrorOnItemContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created without Name!.
        /// </summary>
        public static string ApiConnectorErrorOnItemCreatedWOName {
            get {
                return ResourceManager.GetString("ApiConnectorErrorOnItemCreatedWOName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not created!.
        /// </summary>
        public static string ApiConnectorErrorOnItemNotCreated {
            get {
                return ResourceManager.GetString("ApiConnectorErrorOnItemNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to try again (without an employee set)?.
        /// </summary>
        public static string ApiConnectorErrorOnItemTryAgain {
            get {
                return ResourceManager.GetString("ApiConnectorErrorOnItemTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not detect the name of the repository. 
        ///Is the correct name?.
        /// </summary>
        public static string ApiConnectorNameNotFound {
            get {
                return ResourceManager.GetString("ApiConnectorNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WICHTIG! Dieses Vorgehen ist nur nötig, falls das Backlog über den normalen 
        ///Programmablauf nicht zu finden ist. 
        ///1.  Backlog öffnen
        ///2.  F12 drücken und zu Netzwerkanalyse (Chrome: Network) navigieren.
        /// </summary>
        public static string ApiInstructionsColumn1 {
            get {
                return ResourceManager.GetString("ApiInstructionsColumn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.  Ein neues Epic anlegen (kann danach wieder gelöscht werden)
        ///4.  Die Anfrage &apos;updateWorkItems&apos; auswählen und auf &apos;Anfrage&apos; (Chrome: &apos;Preview&apos;) navigieren
        ///5.  Hinterste Nummern eintragen (hier: teamId =315, projectId =507).
        /// </summary>
        public static string ApiInstructionsColumn2 {
            get {
                return ResourceManager.GetString("ApiInstructionsColumn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while Reading the Backlog.
        /// </summary>
        public static string BacklogCompareviewModelErrorGetBacklog {
            get {
                return ResourceManager.GetString("BacklogCompareviewModelErrorGetBacklog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backlog successfully read. Comparing Data....
        /// </summary>
        public static string BacklogCompareviewModelSuccessGetBacklog {
            get {
                return ResourceManager.GetString("BacklogCompareviewModelSuccessGetBacklog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to get existing Backlog.
        /// </summary>
        public static string BacklogCompareviewModelTryGetBacklog {
            get {
                return ResourceManager.GetString("BacklogCompareviewModelTryGetBacklog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Backlog.
        /// </summary>
        public static string BacklogViewHeader {
            get {
                return ResourceManager.GetString("BacklogViewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Backlogs.
        /// </summary>
        public static string BacklogViewReadBacklog {
            get {
                return ResourceManager.GetString("BacklogViewReadBacklog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string ButtonBack {
            get {
                return ResourceManager.GetString("ButtonBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string ButtonContinue {
            get {
                return ResourceManager.GetString("ButtonContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ButtonExit {
            get {
                return ResourceManager.GetString("ButtonExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string ButtonStart {
            get {
                return ResourceManager.GetString("ButtonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string DefaultTaskViewButtonOpen {
            get {
                return ResourceManager.GetString("DefaultTaskViewButtonOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string DefaultTaskViewButtonRefresh {
            get {
                return ResourceManager.GetString("DefaultTaskViewButtonRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the Default Task List.
        /// </summary>
        public static string DefaultTaskViewButtonTexts {
            get {
                return ResourceManager.GetString("DefaultTaskViewButtonTexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defaulttasks.
        /// </summary>
        public static string DefaultTaskViewHeader {
            get {
                return ResourceManager.GetString("DefaultTaskViewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Default Tasks to the User-Stories.
        /// </summary>
        public static string DefaultTaskViewInstruction {
            get {
                return ResourceManager.GetString("DefaultTaskViewInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.  Projekt öffnen und auswählen
        ///2.  Im Reiter Reports
        ///3.  Auf P_ProjectReport
        ///4.  Statt fester Zeitraum --&gt; Projektzeitraum auswählen.
        /// </summary>
        public static string ExcelInstructionColumn1 {
            get {
                return ResourceManager.GetString("ExcelInstructionColumn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.  Okay --&gt; Es öffnet sich das Spaltenauswahl Fenster
        ///6.  Bearbeiter und Proj.-Nr./PSP auswählen
        ///7.  Auf Okay --&gt; Report wird erstellt.
        /// </summary>
        public static string ExcelInstructionColumn2 {
            get {
                return ResourceManager.GetString("ExcelInstructionColumn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read File.
        /// </summary>
        public static string ExcelViewButtonReadFile {
            get {
                return ResourceManager.GetString("ExcelViewButtonReadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Input.
        /// </summary>
        public static string ExcelViewHeader {
            get {
                return ResourceManager.GetString("ExcelViewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to export the Report from Axc.
        /// </summary>
        public static string ExcelViewInstruction {
            get {
                return ResourceManager.GetString("ExcelViewInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column for Itemdescriptions:.
        /// </summary>
        public static string ExcelViewItemDescription {
            get {
                return ResourceManager.GetString("ExcelViewItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. B.
        /// </summary>
        public static string ExcelViewItemDescriptionBlankText {
            get {
                return ResourceManager.GetString("ExcelViewItemDescriptionBlankText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set which column contains the Description of the Items..
        /// </summary>
        public static string ExcelViewItemDescriptionToolTip {
            get {
                return ResourceManager.GetString("ExcelViewItemDescriptionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column for Employees assigned (optional):.
        /// </summary>
        public static string ExcelViewItemEmployee {
            get {
                return ResourceManager.GetString("ExcelViewItemEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. C.
        /// </summary>
        public static string ExcelViewItemEmployeeBlankText {
            get {
                return ResourceManager.GetString("ExcelViewItemEmployeeBlankText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Default Employee (if more than 1):.
        /// </summary>
        public static string ExcelViewItemEmployeeDefault {
            get {
                return ResourceManager.GetString("ExcelViewItemEmployeeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set which employee will be assigned to the items, if there is more than one Employee set.
        ///If the set number is greater than the number of employees, the last Employee one will be assigned
        ///Tasks will be copied for each employee assigned..
        /// </summary>
        public static string ExcelViewItemEmployeeDefaultToolTip {
            get {
                return ResourceManager.GetString("ExcelViewItemEmployeeDefaultToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set which column contains the employee, who will be assigned on the items. 
        ///Format: &apos;Lastname, Firstname&apos; Separate multiple employees with a semicolon &apos;;&apos;.
        /// </summary>
        public static string ExcelViewItemEmployeeToolTip {
            get {
                return ResourceManager.GetString("ExcelViewItemEmployeeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column for Itemnumbers:.
        /// </summary>
        public static string ExcelViewItemNumber {
            get {
                return ResourceManager.GetString("ExcelViewItemNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. D.
        /// </summary>
        public static string ExcelViewItemNumberBlankText {
            get {
                return ResourceManager.GetString("ExcelViewItemNumberBlankText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set which column contains the Projectnumber of the Items..
        /// </summary>
        public static string ExcelViewItemNumberToolTip {
            get {
                return ResourceManager.GetString("ExcelViewItemNumberToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting Children for Data....
        /// </summary>
        public static string ExcelViewModelChildren {
            get {
                return ResourceManager.GetString("ExcelViewModelChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading: .
        /// </summary>
        public static string ExcelViewModelReading {
            get {
                return ResourceManager.GetString("ExcelViewModelReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to the Excel-File (.xlsx):.
        /// </summary>
        public static string ExcelViewPath {
            get {
                return ResourceManager.GetString("ExcelViewPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the three dots, then select your Excel File.
        /// </summary>
        public static string ExcelViewPathToolTip {
            get {
                return ResourceManager.GetString("ExcelViewPathToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the Worksheet:.
        /// </summary>
        public static string ExcelViewWorksheetName {
            get {
                return ResourceManager.GetString("ExcelViewWorksheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select which worksheet contains the informations..
        /// </summary>
        public static string ExcelViewWorksheetNameToolTip {
            get {
                return ResourceManager.GetString("ExcelViewWorksheetNameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Itemselection.
        /// </summary>
        public static string ItemSelectViewHeader {
            get {
                return ResourceManager.GetString("ItemSelectViewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select which items should be processed.
        /// </summary>
        public static string ItemSelectViewInstruction {
            get {
                return ResourceManager.GetString("ItemSelectViewInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare with 
        ///existing Backlog.
        /// </summary>
        public static string LoginViewButtonCompare {
            get {
                return ResourceManager.GetString("LoginViewButtonCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create the items.
        /// </summary>
        public static string LoginViewButtonCreate {
            get {
                return ResourceManager.GetString("LoginViewButtonCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credential Input.
        /// </summary>
        public static string LoginViewHeader {
            get {
                return ResourceManager.GetString("LoginViewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to the Backlog:.
        /// </summary>
        public static string LoginViewLink {
            get {
                return ResourceManager.GetString("LoginViewLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://tfs.proleit-ag.local:8080/tfs/*****/*****/_backlogs/backlog/*****/Epics.
        /// </summary>
        public static string LoginViewLinkBlankText {
            get {
                return ResourceManager.GetString("LoginViewLinkBlankText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid Password!.
        /// </summary>
        public static string LoginViewModelMessagePassword {
            get {
                return ResourceManager.GetString("LoginViewModelMessagePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid Proxy Adress or uncheck the Box!.
        /// </summary>
        public static string LoginViewModelMessageProxy {
            get {
                return ResourceManager.GetString("LoginViewModelMessageProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid URL!.
        /// </summary>
        public static string LoginViewModelMessageUrl {
            get {
                return ResourceManager.GetString("LoginViewModelMessageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid Usename!.
        /// </summary>
        public static string LoginViewModelMessageUsername {
            get {
                return ResourceManager.GetString("LoginViewModelMessageUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string LoginViewPassword {
            get {
                return ResourceManager.GetString("LoginViewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Id (optional):.
        /// </summary>
        public static string LoginViewProjectId {
            get {
                return ResourceManager.GetString("LoginViewProjectId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Adress:.
        /// </summary>
        public static string LoginViewProxyAddress {
            get {
                return ResourceManager.GetString("LoginViewProxyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To &apos;Network &amp; Internet&apos; -&gt; &apos;Proxy&apos; to see the Address.
        /// </summary>
        public static string LoginViewProxyBlankText {
            get {
                return ResourceManager.GetString("LoginViewProxyBlankText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this option only if you need a proxy to enter the Backlog..
        /// </summary>
        public static string LoginViewProxyToolTip {
            get {
                return ResourceManager.GetString("LoginViewProxyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Proxy.
        /// </summary>
        public static string LoginViewProxyUse {
            get {
                return ResourceManager.GetString("LoginViewProxyUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Id (optional):.
        /// </summary>
        public static string LoginViewTeamId {
            get {
                return ResourceManager.GetString("LoginViewTeamId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        public static string LoginViewUsername {
            get {
                return ResourceManager.GetString("LoginViewUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to firstname.lastname@proleit.com.
        /// </summary>
        public static string LoginViewUsernameBlankText {
            get {
                return ResourceManager.GetString("LoginViewUsernameBlankText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        public static string MessageAlert {
            get {
                return ResourceManager.GetString("MessageAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageError {
            get {
                return ResourceManager.GetString("MessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establishing Connection to Backlog.
        /// </summary>
        public static string MessageEstablishConnection {
            get {
                return ResourceManager.GetString("MessageEstablishConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished!.
        /// </summary>
        public static string MessageFinished {
            get {
                return ResourceManager.GetString("MessageFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. Check your URL, Credentials and Internet Connection.
        /// </summary>
        public static string MessageLoginError {
            get {
                return ResourceManager.GetString("MessageLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Successfully established.
        /// </summary>
        public static string MessageLoginSuccess {
            get {
                return ResourceManager.GetString("MessageLoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the Application Language to German?
        ///(Default Language: English).
        /// </summary>
        public static string MessageSetLanguage {
            get {
                return ResourceManager.GetString("MessageSetLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Selection.
        /// </summary>
        public static string MessageSetLanguageHeader {
            get {
                return ResourceManager.GetString("MessageSetLanguageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string MessageWarning {
            get {
                return ResourceManager.GetString("MessageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Items.
        /// </summary>
        public static string ProgressViewHeader {
            get {
                return ResourceManager.GetString("ProgressViewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error occured. Please check your Internet Connection..
        /// </summary>
        public static string ProgressViewModelErrorCreating {
            get {
                return ResourceManager.GetString("ProgressViewModelErrorCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to created. Problems occured with:.
        /// </summary>
        public static string ProgressViewModelPartiallyCreating {
            get {
                return ResourceManager.GetString("ProgressViewModelPartiallyCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start with creating.
        /// </summary>
        public static string ProgressViewModelStartCreating {
            get {
                return ResourceManager.GetString("ProgressViewModelStartCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to created successfully..
        /// </summary>
        public static string ProgressViewModelSuccessCreating {
            get {
                return ResourceManager.GetString("ProgressViewModelSuccessCreating", resourceCulture);
            }
        }
    }
}
